<h3>Lista de Cliente</h3>
<p>
    <a class="btn btn-success" href="<?php echo $this->url('application/default', array('controller'=>'Application\Controller\Index','action'=>'new')); ?>"><i class="fa fa-hand-o-left">Novo</i></a>
</p>
<div>
<table class="table">
    <thead>
    <th>ID</th>
    <th>Nome</th>
    <th>Ação</th>
    </thead>
    <tbody>
        <?php //$data = $this->dados;?>
        <?php foreach ($this->dados as $data): ?>
        <tr>
<!--            <td><?php //echo $data[id]; ?></td>
            <td><?php //echo $data[nome]; ?></td>-->
            
            <td><?php echo $data->getId(); ?></td>
            <td><?php echo $data->getNome(); ?></td>
            <td>
                
            </td>

        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</div>